# Generated by Django 6.0 on 2025-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('watering_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
